#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

BRANCH_NAME=$(git symbolic-ref --short HEAD)

ISSUE_NUMBER=$(echo "$BRANCH_NAME" | grep -oE '[0-9]+' | head -n 1)

if [ -n "$ISSUE_NUMBER" ] && [ -n "$1" ]; then
  if ! grep -q "$ISSUE_NUMBER" "$1"; then
    echo " #$ISSUE_NUMBER" >> "$1"
  fi
fi